# 全局推送配置数据
push-data:
  # 1 钉钉机器人
  DingDing:
    Secret: ""
    Token: ""
  # 2 PushPlus
  PushPlus:
    Token: ""
  # 3 Server酱
  Server_Turbo:
    Token: ""
  # 4 邮件、用户侧必须配置接收地址
  Email:
    email_username: "@"
    email_password: ""
    email_address: ""
    email_port: ""

# 程序运行时间（满足此时间才推送信息，否则本地输出），早上7点运行时推送，其余时间运行不推送填07，留空为无论何时都推送
time: ""

# 每位用户随机时间（秒）
range_time: "5-10"

# 腾讯地图api密钥，获取地址经纬度需要
api_token: "UGMBZ-CINWR-DDRW5-W52AK-D3ENK-ZEBRC"

# 是否开启实习报告（打卡成功才会提交）
# 是否开启日报，每日提交
day_report: False
# 是否开启周报，每周日提交
week_report: False
# 是否开启月报，每月30号提交
month_report: False

# 是否开启代理
proxy_enable: False

# 日志，仅支持smtp邮件推送，推送的为简化版日志，详细日志见log内具体文件'''
log_report: False
log_report_data:
    # smtp用户名
    "emailUsername": ""
    # smtp密码
    "emailPassword": ""
    # smtp服务器地址
    "emailAddress": ""
    # smtp端口
    "emailPort": ""
    # 接收日志邮箱
    "Receiver": ""

