name: Python Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -i https://mirrors.aliyun.com/pypi/simple -r requirements.txt

    - name: Run Main.py
      run: python Main.py

    - name: Send Email Notification
      if: always()  # 不论工作流程是否成功都发送通知
      run: |
        echo "Subject: GitHub Actions Status: ${{ job.status }}" > email.txt
        echo "" >> email.txt
        echo "GitHub Actions status: ${{ job.status }}" >> email.txt
        cat email.txt | mail -s "GitHub Actions Status" ${{ secrets.EMAIL_ADDRESS }}
