name: Python Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -i https://mirrors.aliyun.com/pypi/simple -r requirements.txt

    - name: Run Main.py
      run: python Main.py

    - name: Send Email Notification
      if: always()
      run: |
        echo "Subject: GitHub Actions Status: ${{ job.status }}" > email.txt
        echo "" >> email.txt
        echo "GitHub Actions status: ${{ job.status }}" >> email.txt
        if [ ${{ job.status }} == 'success' ]; then
          echo "Congratulations! Your workflow was successful." >> email.txt
        else
          echo "Oops! Something went wrong. Your workflow failed." >> email.txt
        fi
        cat email.txt | smtp-cli --verbose --host=smtp.qq.com --enable-smtps --user=3014586288@qq.com --pass=vaqjmjdbxnfxdcig --from=3014586288@qq.com --to=3014586288@qq.com
