name: Python Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -i https://mirrors.aliyun.com/pypi/simple -r requirements.txt

    - name: Run Main.py
      run: python Main.py

    - name: Send Email Notification
      if: always()
      run: |
        echo "Subject: GitHub Actions 状态: ${{ job.status }}" > email.txt
        echo "" >> email.txt
        echo "GitHub Actions 状态: ${{ job.status }}" >> email.txt
        if [ ${{ job.status }} == 'success' ]; then
          echo "恭喜！你的工作流程运行成功。" >> email.txt
        else
          echo "糟糕！出现了错误，你的工作流程运行失败。" >> email.txt
        fi
        python -c 'import smtplib; from email.mime.text import MIMEText; msg = MIMEText(open("email.txt").read(), _charset="utf-8"); msg["Subject"] = "GitHub Actions 状态"; msg["From"] = "3014586288@qq.com"; msg["To"] = "3014586288@qq.com"; s = smtplib.SMTP_SSL("smtp.qq.com", 465); s.login("3014586288@qq.com", "vaqjmjdbxnfxdcig"); s.sendmail("3014586288@qq.com", ["3014586288@qq.com"], msg.as_string()); s.quit();'
